### ISSUE TITLE
report requesting more flexible to change

### ISSUE THREAD

**Issue by sol-myob** [monajena27/Toy-Block-Factory#10]
https://github.com/monajena27/Toy-Block-Factory/blob/49a364f7e6039d2b1178996a5e9b2f91c94a6959/ToyBlockFactoryKata/ToyBlockFactory.cs#L59

to make this more flexible you can use your enum again

`getReport(Order order, ReportType reportType()`

then we dont need to add a method every time we have a new report

**Comment by mona-jena** [comment]
wait do you mean, have a single GetReport( orderID, ReportType) in ToyblockFactory? 

Or do you mean all the Get...Report() in ToyBlockFactory should take in ReportType too along with order Id?

**Comment by sol-myob** [comment]
yes if it takes in the report type and the order id, then you dont need a method for each report type. then internally  (within the method probably) you can switch on reporttype to determine what to do

**Comment by mona-jena** [comment]
hbn? https://github.com/monajena27/Toy-Block-Factory/blob/fixes/ToyBlockFactoryKata/ReportGenerators/ReportGenerator.cs

**Comment by sol-myob** [comment]
looks good to me without looking under the covers. 

What are you thoughts on this now, esp around flexibility


---
took me a while to figure out how to even see this change, GH didn't take me to it (I assume you copied from the address bar? if you did that often doesnt work out if you share it) 

so I had to work out the branch and find the file

**Comment by sol-myob** [comment]
you generally need to right click in the file and then choose copy permalink for github links to work out when shared

**Comment by sol-myob** [comment]
to files directly that is

**Comment by mona-jena** [comment]
sorry hbn https://github.com/monajena27/Toy-Block-Factory/blob/fixes/ToyBlockFactoryKata/ReportCreators/ReportCreator.cs?

**Comment by sol-myob** [comment]
i found it either way



> looks good to me without looking under the covers.
> 
> What are you thoughts on this now, esp around flexibility
> 
>

**Comment by mona-jena** [comment]
yep its quite flexible can just add a new case statement and method if there is another report type

**Comment by sol-myob** [comment]
impossible to forget to add required parts now too! because it is enum, c# will complain you aren't swtiching on the new enum edition. 

before, you  can forget all the places it needs to be
