### ISSUE TITLE
Generator naming

### ISSUE THREAD

**Issue by sol-myob** [monajena27/Toy-Block-Factory#13]
https://github.com/monajena27/Toy-Block-Factory/blob/49a364f7e6039d2b1178996a5e9b2f91c94a6959/ToyBlockFactoryKata/ReportGenerators/IReportGenerator.cs#L6

I am not the biggest fan of everything being called a generator, mostly because a generator in software is often one of these: [](https://en.wikipedia.org/wiki/Generator_(computer_programming))

there must be a creational word that aligns better with what this does

**Comment by mona-jena** [comment]
what about maker or builder? lol, there aren't a lot of great options for a synonym for generator.

**Comment by sol-myob** [comment]
IReportCreator?
IReportCollator?
IReporter?

**Comment by mona-jena** [comment]
Is the naming confusing now, bec the interface is called IReportCreator which would make sense for ReportCreator to be the one implementing it. But it's actually the Reports themselves that are implementing it. I could change ReportCreator to ReportCollator but then shouldn't the naming be kept consistent if the words mean the same? https://github.com/monajena27/Toy-Block-Factory/tree/49a364f7e6039d2b1178996a5e9b2f91c94a6959/ToyBlockFactoryKata/ReportGenerators

**Comment by sol-myob** [comment]
you're right, something should be called the equivalent of the order system
`OrderManagementSystem.cs` <=> `ReportSystem.cs`
