### ISSUE TITLE
Hideous Beast

### ISSUE THREAD

**Issue by sol-myob** [monajena27/Toy-Block-Factory#15]
https://github.com/monajena27/Toy-Block-Factory/blob/49a364f7e6039d2b1178996a5e9b2f91c94a6959/ToyBlockFactoryConsole/UserInterface.cs#L7

this thing is a hideous beast, almost to the point where it needs its own testing! 

so much repeated code. This might be a good place for deduplication to get rid of the clutter

**Comment by mona-jena** [comment]
i know i know, but it was the fastest way to do it w/o spending too much time on console

**Comment by monajena27** [comment]
I don't even know where to start lol 😅

**Comment by monajena27** [comment]
trying...but still hideous https://github.com/monajena27/Toy-Block-Factory/blob/fixes/ToyBlockFactoryConsole/UserInterface.cs

**Comment by mona-jena** [comment]
still too much duplication? https://github.com/monajena27/Toy-Block-Factory/tree/fixes/ToyBlockFactoryConsole

**Comment by sol-myob** [comment]
yes, but it is looking incredibly better !

**Comment by mona-jena** [comment]
there are too many parts tied to their particular print statements, not sure what else you could condense

**Comment by monajena27** [comment]
here you go https://github.com/monajena27/Toy-Block-Factory/blob/fixes/ToyBlockFactoryConsole/OrderCollector.cs
