### ISSUE TITLE
moving more out of program

### ISSUE THREAD

**Issue by sol-myob** [monajena27/Toy-Block-Factory#16]
https://github.com/monajena27/Toy-Block-Factory/blob/49a364f7e6039d2b1178996a5e9b2f91c94a6959/ToyBlockFactoryConsole/Program.cs#L18

you could move this into its own class too, leaving program light as possible.

**Comment by mona-jena** [comment]
lol adding it to the hideous beast

**Comment by sol-myob** [comment]
perfect :D
