### ISSUE TITLE
misleading this method is

### ISSUE THREAD

**Issue by sol-myob** [monajena27/Toy-Block-Factory#18]
https://github.com/monajena27/Toy-Block-Factory/blob/49a364f7e6039d2b1178996a5e9b2f91c94a6959/ToyBlockFactoryConsole/InputValidator.cs#L8

this method name reads like it does one thing and then returns, but it actually takes over the whole event loop. it should be more clear about that or ideally not do it at all

**Comment by sol-myob** [comment]
Having a open closed crisis, this issue is .

**Comment by mona-jena** [comment]
AskUserWhileEmpty(string input) ?

**Comment by sol-myob** [comment]
nothing else in here is asking the user anything... and its name says its a validator. the thing on the outside can worry about interrogating the user for a correct response

**Comment by mona-jena** [comment]
It's moved now here but don't know if it's any better https://github.com/monajena27/Toy-Block-Factory/blob/fixes/ToyBlockFactoryConsole/OrderCollector.cs

**Comment by sol-myob** [comment]
```c#
Console.Write("Please input the number of x ys: ");
var xy = Console.ReadLine();
for (var i = 0; i < BlockQuantity(xy); i++)
   order.AddBlock(x, y);
```

does that help at all

**Comment by mona-jena** [comment]
is this for this issue or the beast issue?

**Comment by sol-myob** [comment]
my bad.

this one looks more at home here than the other place. I guess that ownership of it this beast must have

**Comment by mona-jena** [comment]
here you go https://github.com/monajena27/Toy-Block-Factory/blob/fixes/ToyBlockFactoryConsole/OrderCollector.cs

**Comment by sol-myob** [comment]
you're basically a magician at this point 🧙‍♀️

**Comment by mona-jena** [comment]
it's hardly magic when you get told the trick lol

**Comment by sol-myob** [comment]
not true! every wizard only becomes a wizard after they first start making things disappear. doesn't matter how they learn it

**Comment by sol-myob** [comment]
there are cleaners, closers and coolers.

today you are a closer that's for sure

**Comment by mona-jena** [comment]
oooh I like that scale! Should use it more often for a time to time progress check
