### ISSUE TITLE
readme run me

### ISSUE THREAD

**Issue by sol-myob** [monajena27/Toy-Block-Factory#19]
your readme should include steps on what is required and how to run your program :)

**Comment by mona-jena** [comment]
I tried following this to be able to run Program.cs from the terminal: https://www.codesdope.com/course/c-sharp-introduction/ and https://stackoverflow.com/questions/49767212/how-to-compile-and-run-c-sharp-project-from-terminal-mac-os but it can't find the namespace ToyBlockFactoryKata. Am I looking at the right thing?

**Comment by sol-myob** [comment]
the problem with the internet is that it's  old.

to run your program at the terminal you need to 
`dotnet restore
dotnet build
dotnet run -p .\ToyBlockFactoryConsole`

from memory. the run needs to specify which project in the solution should be the startup project

if you CSPROJ file already defines this (which it might, but I dont think it did when I tried to run my code locally) then you can just `dotnet run`

you can set the default startup by right clicking the project in the editor and choosing set as startup project
