### ISSUE TITLE
test data naming

### ISSUE THREAD

**Issue by sol-myob** [monajena27/Toy-Block-Factory#3]
https://github.com/monajena27/Toy-Block-Factory/blob/49a364f7e6039d2b1178996a5e9b2f91c94a6959/ToyBlockFactoryTests/CuttingListReportGeneratorTests.cs#L10

I would be inclined to give these actual names  rather than customer1 etc
either describing what test they relate to or the name of the customer. that way they are easier to reference

**Comment by mona-jena** [comment]
Is it necessary even when the customer name doesn't get referenced in any of the tests except for the block of code where the order is created?

**Comment by sol-myob** [comment]
A little context is better than none. Everytime you see a number like that it takes that extra reasoning to remember why is this 3 or X again

As your code grows and more like that pop up it becomes a Burson. Comments are one step in the right direction short term but degrade quickly without static analysis or maintenance

**Comment by sol-myob** [comment]
Why 3.14 ?? You never see it. Always Math.pi

**Comment by mona-jena** [comment]
does this look better? https://github.com/monajena27/Toy-Block-Factory/blob/fixes/ToyBlockFactoryTests/CuttingListReportGeneratorTests.cs

**Comment by sol-myob** [comment]
Yep, now you know not to read too far into it. As soon as you see James, you can just think "James, who gives a f* about James and move on"


Now it just needs to go at the bottom of the file

**Comment by mona-jena** [comment]
But shouldn't the method be closer to its caller, which is the constructor?

**Comment by sol-myob** [comment]
in your functional code, that would make sense (not in every case) but this is a test. the idea of extracting the setup out is to remove clutter, its best for it to be at the bottom to achieve that so that the focus is on what is being tested. if someone needs to dig into the setup, they know where to go
