### ISSUE TITLE
private methods at the bottom

### ISSUE THREAD

**Issue by sol-myob** [monajena27/Toy-Block-Factory#4]
https://github.com/monajena27/Toy-Block-Factory/blob/49a364f7e6039d2b1178996a5e9b2f91c94a6959/ToyBlockFactoryTests/CuttingListReportGeneratorTests.cs#L10

Usually private methods either live close to where they are used (like a public method that calls them) or at the bottom.

in tests they make most sense at the bottom as you wanna see the test cases when you first open a file

**Comment by mona-jena** [comment]
If it's at the bottom, how do you see what the expected is supposed to be for each test? Or you don't care what the exact value is, as long as the test passes?

**Comment by sol-myob** [comment]
excellent question. I agree that you should be able to know what is being asserted and what is expected. I don't think that knowledge should come from it being unavoidably the first thing in the file you see. for example when a test fails in the IDE and I click it takes me there, I would miss this setup no matter where it was, so it only works when opening the file directly.

therefore, should the act/arrange/assert and the data the captures what is being tested live closer to the tests in this case?

**Comment by mona-jena** [comment]
how about now? https://github.com/monajena27/Toy-Block-Factory/blob/fixes/ToyBlockFactoryTests/CuttingReportTests.cs
