### ISSUE TITLE
pricing calc tests

### ISSUE THREAD

**Issue by sol-myob** [monajena27/Toy-Block-Factory#7]
https://github.com/monajena27/Toy-Block-Factory/blob/49a364f7e6039d2b1178996a5e9b2f91c94a6959/ToyBlockFactoryTests/PricingCalculatorTests.cs#L38

I would want to have a separate test and assertion for these. 
Each of the calculations that happen in the pricing is a business rule, and probably an important one at that. if one was to be wrong, I would want to know about it in isolation as well as understand from the test name what it was supposed to be

**Comment by mona-jena** [comment]
There is a similar test in InvoiceReportTests, is that worth being there? If so, should that also be separated?

**Comment by mona-jena** [comment]
better? https://github.com/monajena27/Toy-Block-Factory/blob/fixes/ToyBlockFactoryTests/PricingCalculatorTests.cs

**Comment by sol-myob** [comment]
in this case, the goal is to test it in maximum isolation, as we just want to know it can do prices. because it implements an interface this should be easy via the public methods.

which means you won't need the toyblockfactory. just create it, jam a bunch of blocks into it and make sure the right answer pops out.

you could say there are 2 classes of the test.
1. tests where the aim is to ensure the system solves the problem it is intended to. or more simply that shits wired up right
2. tests where the aim is to show that a component in isolation gives the right output for a given input (the true unit test)

most of your tests are the first, which is great. but the pricing calculator is the 2nd.

often this is a must, when there are a bunch of things wired together say A B C. and each of those things have 20 inputs with 20 expected outputs (say mapping a chart of accounts from one system to another as one example)

in that scenario it is infeasible to test all outcomes when A-B-C are all wired up, the combination of possibilities explodes (combinatorial explosion). so we test A and B and C in isolation. and then have 1 test to show they are wired up

**Comment by mona-jena** [comment]
do you mean having the test pricing calc and using that for tests, does the second kind of tests for you?

**Comment by sol-myob** [comment]
no.

in your case. 
pricing calc and invoice gen we want to test in isolation. Type 2.

toyblock factory we want to make sure all its bits are wired up correctly. Type1.

because we pass the pricing strategy into the toy block, we can isolate it all by itself without needing to touch any other classes in the test. this is ideal because if those things do change, these tests are unaffected

that isnt true for invoice gen. so to get as close to that as possible. we make a stubbed pricing strategy

**Comment by mona-jena** [comment]
does the setup for this also need to be at the bottom?

**Comment by sol-myob** [comment]
private methods, the constructor should still be at the top, and if its big, pull out a method and sink it to the bottom
